steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - calcAngle
  - --source=https://source.developers.google.com/projects/data-engineer-practice-263910/repos/github_jafarshaik6_clocks
  - --runtime
  - python37
  - --trigger-http
  - --allow-unauthenticated
