steps:
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip3 install -r clock_angles/requirements.txt && export PYTHONPATH=`pwd` && pytest -v clock_angles/test/test.py'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["config", "list"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "clock_angles/app.yaml"]
timeout: "1600s"
