from flask import Flask, request, render_template


app = Flask(__name__)

@app.route('/')
def index():
    return render_template("index.html")


@app.route('/', methods=['POST'])
def calculate():

    # Validating blank inputs
    try:
        h = float(request.form['h'])
        m = float(request.form['m'])

        hours = h
        minutes = m

        # Validation for hours and minutes values
        if 0 < h <= 12 and 0 <= m < 60:

            if (h == 12):
                h = 0

            # Calculating angles generated by movement of clock hands from 12
            hour_angle = 0.5 * (h * 60 + m)
            minute_angle = 6 * m

            # Calculating difference between two angles of hours and minutes
            angle = abs(hour_angle - minute_angle)

            # Finding smaller angle
            angle = min(360 - angle, angle)

            return render_template("pass.html", h=hours, m=minutes, a=angle)
        else:
            w = "Oops.. Wrong Input !"
            return render_template("pass.html", h=hours, m=minutes, w=w)

    except:
        w = "Oops.. You submitted blank inputs !"
        return render_template("pass.html", w=w)


if __name__ == '__main__':
    app.run(debug=True)

